kind: Service
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "360"
  name: validation-flow-service
  namespace: validation-flow-migration
spec:
  selector:
    app.kubernetes.io/instance: validation-flow-migration-validation-flow-instance
  ports:
- name: validation-flow-validation-flow 8001 8002
protocol: TCP
port: validation-flow 8001 8002
targetPort: validation-flow 8001 8002
