kind: Service
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "360"
  name: validation-flow-service
  namespace: validation-flow-migration
spec:
  selector:
    app.kubernetes.io/instance: validation-flow-migration-validation-flow-instance
  ports:
{validation-flow
8001
    - name: validation-flow-8001
      protocol: TCP
      port: 8001
      targetPort: 8001
8002}
